version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:xenial
        environment:
          CXX: "clang++-4.0"
          CMAKE_BUILD_TYPE: "Release"
          LD_LIBRARY_PATH: "/root/project/simulator/lib:${LD_LIBRARY_PATH}"
    steps:
      - checkout
      - run:
          name: Environment
          command: |
            git submodule sync --recursive
            git submodule update --recursive --init
            apt update
            apt install -y --no-install-recommends build-essential clang-4.0 llvm-4.0-dev clang-format
            wget "https://cmake.org/files/v3.11/cmake-3.11.1-Linux-x86_64.tar.gz" --no-check-certificate
            tar xf cmake-3.11.1-Linux-x86_64.tar.gz
            cp -r cmake-3.11.1-Linux-x86_64/bin/* /usr/local/bin
            cp -r cmake-3.11.1-Linux-x86_64/share/* /usr/local/share
            mkdir simulator build
      - run:
          name: Run CMake
          working_directory: /root/project/build
          command: |
            cmake .. -DCMAKE_INSTALL_PREFIX=/root/project/simulator
      - run:
          name: Run Make
          working_directory: /root/project/build
          command: |
            make install -j
      - run:
          name: Run Tests
          working_directory: /root/project/simulator/bin
          command: ./tests
